### ISSUE TITLE
ERROR: point to the same directory in the file system.

### ISSUE THREAD

**Issue by BravenxX** [react-native-community/react-native-datetimepicker#57]
I have this problem in Android studio when syncing my project.

ERROR: The modules ['@react-native-community_datetimepicker', 'react-native-datetimepicker'] point to the same directory in the file system.
Each module must have a unique path.

I can run my app anyway but when I create apk Release this error appears: 

> Task :@react-native-community_checkbox:verifyReleaseResources FAILED
FAILURE: Build failed with an exception.

Is there any solution??

**Comment by BravenxX** [comment]
I found this provisional solution if you people don't know how to create a apk still

insted of:

gradlew assembleRelease

do this: 

**gradlew app:assembleRelease**

**Comment by aflahkp** [comment]
> I found this provisional solution if you people don't know how to create a apk still
> 
> insted of:
> 
> gradlew assembleRelease
> 
> do this:
> 
> **gradlew app:assembleRelease**

I have the same issue in gradle build step while running with android studio.
not in gradlew assembleRelease

**Comment by Florent75** [comment]
In my case, it was due to the same two lines defined in  the following files :
- android/app/build.graddle, dependencies :
->  "implementation project(':react-native-datetimepicker')" was declared twice
- android/app/src/main/java/com/ *ProjectName* / MainApplication.java  
-> "new RNDateTimePickerPackage()" was declared twice

then : 
- Stop "react-native start"
- clean build using "./gradlew cleanBuildCache"
- run "react-native start"
- run "react-native run-android"

**Comment by constantlahousse** [comment]
You should check this issue : https://github.com/react-native-community/react-native-datetimepicker/issues/27

Apparently the README is incorrect 😬

**Comment by vonovak** [comment]
> ERROR: The modules ['@react-native-community_datetimepicker', 'react-native-datetimepicker'] point to the same directory in the file system.


you most likely don't need to mention both of the modules but just one. Please open a new issue if the problem persists.
